services:
  - type: web
    name: keycloak-auth
    runtime: docker
    env: docker
    plan: free
    envVars:
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL
        value: ${KC_DB_URL}
      - key: KC_DB_USERNAME
        value: ${KC_DB_USERNAME}
      - key: KC_DB_PASSWORD
        value: ${KC_DB_PASSWORD}
      - key: KEYCLOAK_ADMIN
        value: ${KEYCLOAK_ADMIN}
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: ${KEYCLOAK_ADMIN_PASSWORD}

  - type: postgres
    name: keycloak-db
    plan: free
    diskName: keycloak-db-disk